- name: Tonal Centre
  values:
    - C
    - F
    - Bb
    - Eb
    - Ab
    - Db
    - F#
    - B
    - E
    - A
    - D
- name: Parent Mode
  values:
    - Ionian
    - Dorian
    - Phrygian
    - Lydian
    - Mixolydian
    - Aeolian
    - Locrian
- name: Tempo
  values:
    - '70'
    - '80'
    - '90'
    - '100'
    - '110'
    - '120'
- name: Genre
  values:
    - Death Metal
    - Neo Classical Rock
    - Yacht Rock
    - Disco
    - Post Bop Jazz
    - Coffee House Jazz
- name: Time Signature
  values:
    - 2/2
    - 3/4
    - 4/4
    - 5/4
    - 6/8
    - 13/16
